"""
8-Puzzle environment with A* solver.

The 8-puzzle is a 3×3 sliding-tile puzzle where tiles numbered 1–8 are
arranged on a board with one blank cell (represented as 0). The goal state is:

    1 2 3
    4 5 6
    7 8 0

The solver uses A* search with the Manhattan-distance heuristic.
Puzzles are generated by scrambling the goal state a configurable number of
random moves (5–30), guaranteeing solvability.
"""

import heapq
import random
from typing import List, Optional, Tuple

import numpy as np

# Goal configuration
GOAL_STATE = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 0]], dtype=np.int32)

# Directions: the blank moves in these directions.
# We label the *action* by the tile that slides into the blank.
# action index = position in this list
DIRECTIONS = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # up, down, left, right
ACTION_NAMES = ["up", "down", "left", "right"]

# For the model, we use 9 classes: action = index of tile that moved (1-8),
# or 0 for no-op. In practice during training every label will be 0–8
# representing which tile position the blank swaps with.
# We'll encode actions as the flat index (0..8) of the cell that swaps with blank.


def _find_blank(state: np.ndarray) -> Tuple[int, int]:
    """Return (row, col) of the blank (0) cell."""
    pos = np.argwhere(state == 0)
    return int(pos[0, 0]), int(pos[0, 1])


def _manhattan_distance(state: np.ndarray) -> int:
    """Sum of Manhattan distances of each tile from its goal position."""
    dist = 0
    for val in range(1, 9):
        # Current position
        cr, cc = np.argwhere(state == val)[0]
        # Goal position
        gr, gc = np.argwhere(GOAL_STATE == val)[0]
        dist += abs(cr - gr) + abs(cc - gc)
    return dist


def _state_to_tuple(state: np.ndarray) -> tuple:
    """Convert 3×3 array to a hashable tuple."""
    return tuple(state.flatten())


def _get_neighbours(state: np.ndarray) -> List[Tuple[np.ndarray, int]]:
    """
    Return list of (new_state, action) pairs.
    Action = flat index (0..8) of the cell that the blank swaps with.
    """
    br, bc = _find_blank(state)
    neighbours = []
    for dr, dc in DIRECTIONS:
        nr, nc = br + dr, bc + dc
        if 0 <= nr < 3 and 0 <= nc < 3:
            new_state = state.copy()
            new_state[br, bc] = new_state[nr, nc]
            new_state[nr, nc] = 0
            # Action = flat index of the cell that moved into the blank
            action = nr * 3 + nc
            neighbours.append((new_state, action))
    return neighbours


def solve_puzzle(state: np.ndarray) -> Optional[List[int]]:
    """
    Solve the 8-puzzle from `state` using A* with Manhattan distance.

    Args:
        state: 3×3 numpy array with tiles 0–8 (0 = blank).

    Returns:
        List of actions (flat indices 0–8 of the cell swapped with blank
        at each step), or None if unsolvable.
    """
    start = _state_to_tuple(state)
    goal = _state_to_tuple(GOAL_STATE)

    if start == goal:
        return []

    # Priority queue: (f_score, counter, state_tuple, action_list)
    counter = 0
    h = _manhattan_distance(state)
    open_set = [(h, counter, start, [])]
    g_scores = {start: 0}

    while open_set:
        f, _, current_tuple, actions = heapq.heappop(open_set)
        current = np.array(current_tuple, dtype=np.int32).reshape(3, 3)

        if current_tuple == goal:
            return actions

        g = g_scores[current_tuple]

        for new_state, action in _get_neighbours(current):
            new_tuple = _state_to_tuple(new_state)
            new_g = g + 1

            if new_tuple not in g_scores or new_g < g_scores[new_tuple]:
                g_scores[new_tuple] = new_g
                h = _manhattan_distance(new_state)
                counter += 1
                heapq.heappush(open_set, (new_g + h, counter, new_tuple, actions + [action]))

    return None  # unsolvable


def scramble_puzzle(
    num_moves: int = 20,
    seed: Optional[int] = None,
) -> Tuple[np.ndarray, List[int]]:
    """
    Generate a puzzle by scrambling the goal state with `num_moves` random moves,
    then solve it with A* to get the optimal solution.

    Args:
        num_moves: Number of random scramble moves.
        seed:      RNG seed.

    Returns:
        (scrambled_state, optimal_actions)
    """
    if seed is not None:
        random.seed(seed)

    state = GOAL_STATE.copy()

    # Scramble by making random valid moves
    for _ in range(num_moves):
        neighbours = _get_neighbours(state)
        new_state, _ = random.choice(neighbours)
        state = new_state

    # Solve from the scrambled state
    actions = solve_puzzle(state)
    assert actions is not None, "Scrambled puzzle must be solvable."
    return state, actions
